Initial DB setup
Ale573/DisasterAid_4115 pull request #2
Opened 2020-04-30 21:56 UTC by javierbustillo

Para accesar la base de dato, se usaria postgresql con un ORM por encima. El ORM solo se accesara dentro de los DAO, la gente llama los metodos de cada "modelo" para trabajar con DB. 

Para inicializar la base de dato primero crea un DB nuevo que se llame DisasterAid
Luego correr el script que se llama setUpDB.py

2020-04-30 23:04 UTC, Ale573 reviewed
Intente correrlo en mi PC y me esta dando el siguiente error cuando intento ejecutar algun route usando Postman: 
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class User-&gt;user, expression 'Request' failed to locate a name ('Request'). If this is a class name, consider adding this relationship() to the &lt;class 'dao.user.User'&gt; class after both dependent classes have been defined.

No se si se debe a la estructura de dao, handler y routes. 
Vi que cambiaste insert por create, pero a create no le faltarian parametros?

2020-04-30 23:07 UTC, Everod52 requested changes

2020-04-30 23:07 UTC, Everod52 commented on dao/donation.py
> +class Donation(db.Model):
The relation of the donations made by a user is missing.

2020-04-30 23:07 UTC, Everod52 commented on dao/user.py
> +class User(db.Model):
The backref of the donations made by a user is missing.

2020-04-30 23:07 UTC, Everod52 commented on dao/user.py
> +    password = db.Column(db.String(100), nullable=False)
I noticed that Login table is not found, but you added the fields to the User table. I think is a good idea since it's only two single fields, but for the purpose of the project maybe it's easier for the Login group. If we decide to do this change we must alter the ER diagram and notify the other groups.

On another note, I think the capacity of characters for the username should be more. Maybe 20-25 characters.

2020-04-30 23:07 UTC, Everod52 commented on config/__init__.py
> +DEV_DB = 'postgresql://postgres:postgres@localhost/DisasterAid'
Change db user to insouser

2020-04-30 23:11 UTC, javierbustillo commented
> Intente correrlo en mi PC y me esta dando el siguiente error cuando intento ejecutar algun route usando Postman:
> sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class User->user, expression 'Request' failed to locate a name ('Request'). If this is a class name, consider adding this relationship() to the <class 'dao.user.User'> class after both dependent classes have been defined.
> 
> No se si se debe a la estructura de dao, handler y routes.
> Vi que cambiaste insert por create, pero a create no le faltarian parametros?

Voy a verificar el error, pero para create depende de que se inicialize un user por ejemplo

`user = User(firstName="Javier", lastName="Bustillo" . . .)`
`user.create()`

Ahi se añade a la base de datos

2020-04-30 23:17 UTC, javierbustillo commented
> Intente correrlo en mi PC y me esta dando el siguiente error cuando intento ejecutar algun route usando Postman:
> sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class User->user, expression 'Request' failed to locate a name ('Request'). If this is a class name, consider adding this relationship() to the <class 'dao.user.User'> class after both dependent classes have been defined.
> 
> No se si se debe a la estructura de dao, handler y routes.
> Vi que cambiaste insert por create, pero a create no le faltarian parametros?

Ya arregle el error

2020-05-02 22:20 UTC, jaortiz117 commented on dao/user.py
> +    password = db.Column(db.String(100), nullable=False)
I agree

2020-05-02 22:24 UTC, jaortiz117 approved these changes
I like the backend model you guys have going on!

2020-05-02 23:45 UTC, Everod52 approved these changes
Nice job! 
Note: The biggest change here is that the Login model is not implemented but the username and password fields are defined in the User Model.

2020-05-03 00:06 UTC, Ale573 approved these changes
Now it is working. I can connect to the DB. Nice job!

2020-05-03 04:05 UTC, merged